### ISSUE TITLE
Add ndkVersion with static value to build.gradle for newer+reproducible NDK usage

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#101]
it's better to declare the version of the ndk with `ndkVersion` property in build.gradle, thus helping to reproducible builds as the build will ask for the specified ndk version instead of using whats installed on the machine or some default version which is old.

see "Configure specific versions of the NDK in your project" for more details: https://developer.android.com/studio/projects/install-ndk#apply-specific-version

The versions of NDK are: https://developer.android.com/ndk/downloads
Currently the latest stable release is: 22.1.7171670 https://developer.android.com/ndk/downloads#stable-downloads

The docker directory contain manual installation for older version `21.4.7075529`
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/docker/Dockerfile.verifyandroidbuild#L20

Adding the `ndkVersion` will make building with the docker container or otherwise to use the same version.

**Comment by rhrusha** [comment]
We are currently redesigning our CI / CD process to improve the unification of builds and minimize the differences between internal and public processes, as well as increase the transparency of development. 
This and other recommendations will apply in the updated CI / CD
