### ISSUE TITLE
Remove android.enableJetifier line from gradle.properties & npx jetifier calls

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#102]
android.enableJetifier=true
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/android/gradle.properties#L22

see this guide for the steps to ensure it's safe to remove this lines (check that all deps are already fully migrated to AndroidX)
https://medium.com/dipien/say-bye-bye-to-android-jetifier-a7e0d388f5d6

There also calls to `npx jetifier` at:
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/package.json#L11
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/docker/Dockerfile.androidprebuild#L40
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/readme.md#L56

Both can be removed if project+deps fully migrated to AndroidX, also from https://www.npmjs.com/package/jetifier

> Note that jetifier is included and ran automatically with react-native-community/cli for React Native versions 0.60 and above, so you do not need to install and run jetifier manually.

**Comment by rhrusha** [comment]
Checking this with developers. 

Thank you.

**Comment by rhrusha** [comment]
Unfortunately we can't remove Jetifier for now. We will get back to this issue later.
