### ISSUE TITLE
Enable gradle dependency verification

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#103]
This is done by having `./android/gradle/verification-metadata.xml` file, more information:
https://docs.gradle.org/current/userguide/dependency_verification.html

**Comment by rhrusha** [comment]
Hi Emanuel,

This file will be added in the next release after internal tests. 

Thank you for your help.

**Comment by rhrusha** [comment]
unfortunately we can't enable enable gradle dependency verification at this moment.
