### ISSUE TITLE
Remove JCenter lines from build.gradle or at least specify what used by it directly

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#105]
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/android/build.gradle#L13
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/android/build.gradle#L43

Jcenter service is closed (currently in read-only mode, no updates for packages will be made)
more details on needed migration:
https://developer.android.com/studio/build/jcenter-migration

and here content on how to migrate:
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

I also suggest to consider first fixing #103 which make easier to see all deps downloaded by gradle and thus locate the deps that need fixing (contact vendor, etc..) and what versions are used (thus the migration diff will show if dep downgraded in migration which is unlikely but possible if jcenter has newer version then in mavenCentral)

You can declare specific usages of jcenter like explained in https://jeroenmols.com/blog/2021/02/04/migratingjcenter/#consumed-dependencies-from-bintrayjcenter and like it's done for example in this PR of unstoppable wallet "Gradually migrate from jcenter to mavenCentral"
https://github.com/horizontalsystems/unstoppable-wallet-android/pull/3752/files

**Comment by rhrusha** [comment]
I will discuss this with our developers and remove it in next release if it's not needed.

**Comment by rhrusha** [comment]
I have replaced lines to specify what exactly is used from JCenter.

Thank you for the help.
