### ISSUE TITLE
Declare specific version for CMake in build.gradle for newer+reproducible CMAKE usage

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#107]
https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/docker/Dockerfile.verifyandroidbuild#L21

cmake newest from sdkmanager is: 3.18.1

By declaring a specific version for cmake in build.gradle, see:
https://developer.android.com/studio/projects/install-ndk#vanilla_cmake
a newer version can be declared, also using static value will help to reproducible-builds as well as the same version will be used as declared in build.gradle file when compiled even outside the docker in this repo.

**Comment by rhrusha** [comment]
We are currently redesigning our CI / CD process to improve the unification of builds and minimize the differences between internal and public processes, as well as increase the transparency of development. This and other recommendations we will apply in the updated CI / CD
