### ISSUE TITLE
Submodules wallettests&walletinternals are private instead of public (behind authentication)

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#108]
From `.git/config` after cloning this repo:

```
[submodule "__tests__"]
	url = https://github.com/Trustee/wallettests.git
[submodule "walletinternals"]
	url = https://github.com/Trustee/walletinternals.git
```

They declared in .gitmodules file: https://github.com/trustee-wallet/trusteeWallet/blob/master/.gitmodules

Cloning above URLs require authentication, same when recursive cloning this repo.

What are the wallettests & walletinternals repos? is there a reason they private instead of public?

**Comment by Turtus** [comment]
yes its our internal repos for building app tests for autodelivery

internals contains keys to google and apple delivery,
tests includes wallets with real coins private keys(
