### ISSUE TITLE
Реферальная ссылка

### ISSUE THREAD

**Issue by doc4comp** [trustee-wallet/trusteeWallet#11]
Хотелось бы при распространении реферальной ссылки, видеть какое-то превью проекта в виде логотипа например.

**Comment by rhrusha** [comment]
Уточните что вы имеет ввиду, где именно вы хотите видеть превью проекта?

**Comment by doc4comp** [comment]
При копировании ссылки, во многих месенджерах идёт превью страницы с логотипом, т.е. не голая ссылка, а лого проекта в виде изображения со ссылкой.

**Comment by Turtus** [comment]
сделали да)
