### ISSUE TITLE
Missing Code for latest version 1.40.865 in stores

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#110]
https://play.google.com/store/apps/details?id=com.trusteewallet
Updated: June 24, 2021
Current Version: 1.40.865

https://apps.apple.com/us/app/id1462924276

Updated: Jun 24, 2021
Current Version: 1.40.865

While the code in repo is for previous release: 1.40.829

https://github.com/trustee-wallet/trusteeWallet/blob/b4bde9793a45a6b8bb3e9ca5ccc6aba8c8700b88/android/app/build.gradle#L136
https://github.com/trustee-wallet/trusteeWallet/blob/cc26923bbd86e9c133b104dd4eaba69ed2ea8985/ios/trusteewallet/Info.plist#L29-L30

Please ensure the source-code is published in this repo to master branch before related version is uploaded to google-play, and it's tagged with git tag & github releases is used with uploading .ipa+.apk files as assets, as was done for previous version: 1.40.829 https://github.com/trustee-wallet/trusteeWallet/releases/tag/v1.40.829

**Comment by Turtus** [comment]
please @rhrusha describe to Emanuel our build system and tags you have added should be upped already

**Comment by emanuelb** [comment]
Closing as source-code was published for version 1.40.865 which is what on GooglePlay in commit at dev branch:
https://github.com/trustee-wallet/trusteeWallet/commit/e5464112b542d0b801cd911fe16f90dd2fe64933#diff-9526ccfd1d1813ed49c39f8c54dbeb512607376a007d824b905bc8b4e4d202d9

Still no git tag & github release was created for this version.
