### ISSUE TITLE
Не точное отображение сумм в "истории транзакций"

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#12]
Показана сумма 0.0861, при этом точная 0.08609800. Такое округление сбивает с толку, получается бухгалтерия с погрешностью, если смотреть на отображаемые числа. Лучше ничего не округлять, просто сокращать количество отображаемых чисел.
 [https://blockchair.com/bitcoin/transaction/644b5d709a058a3b848623b80d13887bb34ff78b367b24877fb349f8a893a5f5](url)

![photo_2020-03-18_16-31-01](https://user-images.githubusercontent.com/12554812/76971494-ed154a00-6935-11ea-8296-3b4e4adc1c9d.jpg)

**Comment by Turtus** [comment]
кстати - уже сделали, для мелких транз будет писать ...546 satoshi
