### ISSUE TITLE
Amenities on the Wallet Connect page 

### ISSUE THREAD

**Issue by cryptohohol** [trustee-wallet/trusteeWallet#124]
![Screenshot_20211029-220513](https://user-images.githubusercontent.com/93511473/139639082-0ab67df2-b335-47a7-9dd8-5e3fb8077241.jpg)
 For each of the coins Add direct links to connect with DeFi platforms and DEX exchangers.  As an example

**Comment by Turtus** [comment]
and how should it work without dapp browser? we not considering adding browser into mobile wallet as it restricted in apple market etc

**Comment by cryptohohol** [comment]
Та я не говорил про браузер. 
Заделать линии,  при нажатии пусть будет предупреждение (как сейчас при переходе на обозреватель , типа вы переходите на на сторонний сайт ) дальше уже переход по ссылке в любой браузер пользователя, ну и далее как при любом подключении с валлет коннект,  хоть по линку хоть по QR  коду.

**Comment by Turtus** [comment]
ну как оно должно в любой перейти? как передать подключение? как найти кнопку вызова подключения на этом сайте? ну йо - просто нашлепать линков в приложении - это вообще не наша тема, можно обсудить отдельно в чате с мишей и тд - но я не понимаю зачем и более того это просто ... будет
