### ISSUE TITLE
Идеи и предложения

### ISSUE THREAD

**Issue by Kotikstar** [trustee-wallet/trusteeWallet#125]
1. Создать/выпустить карту (Visa, MasterCard).
2. Выпустить десктопное приложение Trustee Wallet.
3. Создать 2FA или U2F, или оба.
4. Выложить приложение в AppGallery для телефонов без гугл сервисов и т.д https://developer.huawei.com/consumer/ru/appgallery/

**Comment by Turtus** [comment]
из этого -в работе 2 уже - как раз к нг альфа будет, по остальным
1.3. мы некастодиальный кошелек
4. не было времени - задача висит уже
