### ISSUE TITLE
Создание мерчанта для оплаты

### ISSUE THREAD

**Issue by Kotikstar** [trustee-wallet/trusteeWallet#127]
Предлагаю создать мерчант для приёмов оплаты и по желанию плагин для его интеграции в популярных CMS по типу Wordpress, DLE, Joomla и т.д

**Comment by Turtus** [comment]
мы не держим балансов пользователей - поэтому технически принимать оплату не можем - возможно в партнерстве с кем-то - на данный момент мы некастодиальны более чем полностью
