### ISSUE TITLE
#UX Отображение истории

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#13]
Предлагаю не дублировать одни и те же числа, а просто отображать блок "Продажа". При этом подробности, в том числе и данные исходящей транзакции, показывать в развернутой информации. Иначе дубли цифр сбивают с толку, путают юзеров. 

![photo_2020-03-18_16-58-40](https://user-images.githubusercontent.com/12554812/76975328-11bff080-693b-11ea-854a-f04b45ecd789.jpg)

**Comment by Turtus** [comment]
в новой версии уже именно так работает - изначально так и хотели, но тк продажи у нас идут через разных провайдеров - мы их берем отдельно и потом состыковываем транзакции на кошельке и операции у провайдеров
