### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by CEO-NextMindCoin** [trustee-wallet/trusteeWallet#135]
Hello team Trustee,
Here is the French translation of your application. Could you help me please I FORK your project and I can not put my information in the support page. Is this good in BlocksoftExternalSettings.js? i have tried but it doesnt work. Thank you and nice work for your wallet.

https://www.sendspace.com/file/a75mrj
[fr.json.zip](https://github.com/trustee-wallet/trusteeWallet/files/7654024/fr.json.zip)
[fr.json.zip](https://github.com/trustee-wallet/trusteeWallet/files/7654025/fr.json.zip)

**Comment by Turtus** [comment]
if you run on emulator https://github.com/trustee-wallet/trusteeWallet/pull/134/files code you will see external settings could be rewrited from server when we have some troubles with nodes etc - and email is also changable... you could redirect to your server link or disable rewriting  https://github.com/trustee-wallet/trusteeWallet/blob/dbb94e36d79f3901fb81894174739ba435dd869c/crypto/common/BlocksoftExternalSettings.js#L154 here

**Comment by Turtus** [comment]
ps french translation file will be rechecked in separated merge )

**Comment by CEO-NextMindCoin** [comment]
Thank you Turtus, for your answer which helped me a lot. Do you want me to redo a pull request on the DEV branch with only the French translator file?

I have one last problem I added the logo of my token here:
NXMC-Wallet / assets / images / currency /

But I can't see it in the app. Which file to modify to have it displayed in the application without needing to paste the token contract? Thanks a lot for your help. Good day

**Comment by Turtus** [comment]
1) file i will add after some review -  you can do or i will anyway need to review with our main "text" manager
2) icons are built in font - now its complex to do - i will ask for small guide here @ShchipskiiYura

**Comment by Turtus** [comment]
how to chage default icons in application

1. Import file assets/jsons/fonts/selection.json to site https://icomoon.io/app
2. Add need icon to colection
3. Download new icons package
4. Replace next files in source code:
  - trusteewallet/android/app/src/main/assets/fonts/icomoon.ttf;
  - trusteewallet/assets/fonts/icomoon.ttf;
  - assets/jsons/fonts/selection.json;
from dowloads package
5. Restart app local server.
6. Add your icon to app with CustomIcon component

Also, remember add icons colors for light and dark theme if you add coin/token icon.

**Comment by CEO-NextMindCoin** [comment]
Thank you very much Turtus. You are a really nice person

**Comment by Turtus** [comment]
done
