### ISSUE TITLE
#UX Стилистика и элементы 

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#14]
Предлагаю удалить надписи и иконки "копировать" там где это и так интуитивно понятно. 
Зачем нужны надпись и иконка "Копировать", если функция копирования работает при тапе по адресу? При этом,  это же реализованно без надписи и иконки в разделе "Получить" (в бета версии)
![photo_2020-03-18_17-36-08](https://user-images.githubusercontent.com/12554812/76978133-0078e300-693f-11ea-86f7-c61259e8b037.jpg)
...  При необходимости скопировать адрес юзер интуитивно будет пробовать сделать это тапом по адресу, это стандартная попытка выделения и копирования. Если есть надпись "Копировать" то юзер будет целиться в нее, что не хорошо и не плохо... При этом это режет глаз выбиваясь из  стиля, так как в других местах это реализованно без надписей и иконок.

**Comment by Turtus** [comment]
сделано
