### ISSUE TITLE
XRP ledger not loading

### ISSUE THREAD

**Issue by glskep** [trustee-wallet/trusteeWallet#144]
No transactions previous or new, are showing in the app.

**Comment by Turtus** [comment]
thanks for report - i will check xrp node we are using and fix if its problem

also i suggest trying vpn - some of our users now suffering from different providers restrictions

**Comment by Turtus** [comment]
after tests - usually ok - sometimes - vpn will fix it if too often 

https://xrplcluster.com "<html>\r\n<head><title>503 service temporarily unavailable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>503 service temporarily unavailable</h1></center>\r\n<hr><center>cloudflare-nginx</center>\r\n</body>\r\n</html>\r\n" request failed with status code 503 empty data
