### ISSUE TITLE
0x call data after transaction Speed Up on Ethereum (Dropped & Replaced)

### ISSUE THREAD

**Issue by ohld** [trustee-wallet/trusteeWallet#149]
Hey! 

**One user of your wallet** tried to call swap contracts via our website:
https://etherscan.io/tx/0x6f494884fcd389413c1e53ed966d49d89e90853227eedab750d07011add681e5

The transaction stuck because of the low gas price and then he/she decided to speed up it. As a result, **the call data become empty**:
https://etherscan.io/tx/0x8fa842a7ce802a2bad57a71d2232f35554a92e3fe43d0850cf6a3e64c527a77f?from=trustee

This is definitely a bug with your wallet since this is the case we see only with TrusteeWallet users. 

One more question to think of:
Your user lost his $122 because after the speedup he transferred tokens to a [XY Finance](https://xy.finance/) contract which doesn't have the ability to withdraw tokens from balance if they were sent with `0x` call data. Who will refund tokens to a user? We don't have any contracts - our website just gives a simple UI to call other contracts. XY Finance contracts just don't expect 0x call data and don't have refund methods for it.

By the way, [Via Protocol](https://via.exchange) is an aggregator for a huge number of bridges/dexes across 15+ blockchains. We have [JS SDK](https://github.com/viaprotocol/via-sdk-js) which may be useful for your wallet.

**Comment by Turtus** [comment]
first of all = 0x data is not one that is sending tokens as token transfer is call of function that is actually posted in data field of transaction... as we have a lot of users who is using Trustee for tokens transfer etc - and speeding up - i dont think its usual bug, but i will check. 
also please check provide first transaction data (its already not in blockchain) and add some logic on default "sendToAddress" as its simple revert function

**Comment by Turtus** [comment]
fixed ui a little bit - tested for a while now, so could be closed
