### ISSUE TITLE
#UI История транзакций

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#15]
Какую цель преследуют элементы выделенные на скрине? :
![photo_2020-03-18_17-40-11](https://user-images.githubusercontent.com/12554812/76978741-c2c88a00-693f-11ea-8d30-8115f36b21ad.jpg)
Зачем это украшение? Элементы сильно отвлекают, занимают место, делают дизайн грязным. Ведь "история транзакций" это бухгалтерия, здесь важны сухие данные.
 Итак, у нас уже есть информация: "Входящая, исходящая, или покупка, продажа", рядом с каждым числом имеем оператор + , или - . Этого более чем достаточно для понимания о типе действий с балансом кошелька. Лишние элементы лишь отвлекают.

**Comment by Turtus** [comment]
не актуально - дизайн уже поменяли немного
