### ISSUE TITLE
A question about the price data privider

### ISSUE THREAD

**Issue by Gmlogy** [trustee-wallet/trusteeWallet#158]
Hi there, 
from where the app get the prices and rates for coins ? I mean the provider like Coingeko or CMC....

**Comment by Turtus** [comment]
we use both - for coins which ones are on CMC - CMC, for others and for rechecks - coingeko, plus binance and other price providers

**Comment by Gmlogy** [comment]
thanks for your reply. i see, Please can you tell me all the other providers
