### ISSUE TITLE
Новая покупка, отображение кнопки "оплатить"

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#16]
Успешно совершена покупка, но при этом в раскрытом блоке транзакции отображается кнопка "оплатить". Сбивает с толку. При попытке оплатить, система говорит об успехе и созданном ордере. Так зачем же показывать "оплатить"? Другое дело если транзакция реально не оплачена. 
![photo_2020-03-18_18-20-20](https://user-images.githubusercontent.com/12554812/76983220-b3e4d600-6945-11ea-9602-b6b2eae09a03.jpg)

**Comment by Marabun** [comment]
Если покупка не оплачена, вместо примечания "новая" писать "не оплачена". Так понятнее ее статус. 
![photo_2020-03-18_18-30-42](https://user-images.githubusercontent.com/12554812/76984293-4c2f8a80-6947-11ea-8ebc-f248efe8ae5d.jpg)

**Comment by Turtus** [comment]
done! улучшили в новом дизайне - только последние неоплаченные висят и то недолго - это пока не дойдет в системе
