### ISSUE TITLE
WalletConnectV2 implemention

### ISSUE THREAD

**Issue by manianrezaie** [trustee-wallet/trusteeWallet#169]
Please update walletconnect sdk to Verion2. thanks

**Comment by Turtus** [comment]
we have been testing it already - so here it is https://github.com/trustee-wallet/trusteeWallet/releases/tag/v1.51.5

**Comment by Turtus** [comment]
done https://github.com/trustee-wallet/trusteeWallet/commit/721e0c7749dfdc9534f04287b3f09b3a5f61931a
