### ISSUE TITLE
#UX История транзакций, "Показать еще"

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#17]
Возможно ли сделать непрерывный скролинг без необходимости нажимать "Показать еще"? Это очень неудобно, кода много транзакций и нужно быстро добраться до более старых. 

![photo_2020-03-18_18-46-01](https://user-images.githubusercontent.com/12554812/76985639-3753f680-6949-11ea-8209-7ff8c46af46c.jpg)

**Comment by Turtus** [comment]
done build 828 +
