### ISSUE TITLE
`java.lang.NoClassDefFoundError: javax/annotation/Generated` While trying to run the app on android using `yarn android`

### ISSUE THREAD

**Issue by dhruvja** [trustee-wallet/trusteeWallet#171]
I am trying to run the app on android emulator, but when i tried running i got the error below
```
* What went wrong:
Execution failed for task ':fioprotocol_fiosdk:compileDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: javax/annotation/Generated
```

I referred to this https://github.com/querydsl/querydsl/issues/2242 but it didnt solve the error.

Please help me on how i can solve this error and have the app running?

**Comment by Turtus** [comment]
for emulator you can disable it by removing fio from package.json (after installation all modules by `jest install`) but for more clever answer we need to know emulator / sdk versions @rhrusha will check

**Comment by dhruvja** [comment]
Thanks a lot, removing the package made it work.
