### ISSUE TITLE
Below is the quick user guide of BEP-283 pr.

### ISSUE THREAD

**Issue by A1985J09** [trustee-wallet/trusteeWallet#176]
Below is the quick user guide of BEP-283 pr.
### Mainnet/Testnet

If you run a mainnet or testnet node, you just run your node with a new flag `--history-segment` . It will use hard code history segment to auto prune useless ancient data(except tx index) when node restart.

```bash
./bsc --config "./node/config.toml" --rpc.allow-unprotected-txs --allow-insecure-unlock --gcmode full --syncmode snap --ws --datadir "./node/data-seed" --metrics --metrics.addr 0.0.0.0 --metrics.port 6062 --pprof --pprof.port 6072 --http.corsdomain "*" --maxpeers 500 --history.transactions 0 --metrics.expensive --history-segment
```

Default segment config as below:

| Parameter | Value | Description |
| ---| ---| --- |
| BoundStartBlock | 31,268,600 | The starting block height of the first segment. |
| HistorySegmentLength | 2,592,000 | assume 1 block for every 3 second, 2,592,000 blocks will be produced in 90 days. |

There are also provide a offline prune tool, it will prune tx index too.

```bash
./bsc prune-history-segments --datadir {dataDir}
```

It is also compatible with `pruneancient` & `prune-block` feature.

#### Snap Sync

If you start snap sync from genesis, the node will only download latest 2 segments blocks.

![image](https://github.com/bnb-chain/BEPs/assets/124862913/0e9a623b-a808-4240-b015-bf2ecfeb67d1)

### Private Network

If you run a private network, you could export & import your custom history segment file.

*   export history segment config, specific segment `boundstart` block, and `segmentlen` .

```bash
./bsc export-segment --datadir {dataDir} --history-segment.output ./history_segments.json --history-segment.boundstart 31268530 --history-segment.segmentlen 1000000
```

*   run node with custom history segment, with flag `--history-segment --history-segment.custom ./history_segments.json` .
*   prune ancient data.

```bash
./bsc prune-history-segments --datadir {dataDir} --history-segment.custom ./history_segments.json
```

> Attention: history segment need `Luban` hardfork.

## Storage Profile

| Type | DIsk Usage | Storage Size |
| ---| ---| --- |
| Normal Node | 2.2 T | 2.41 T |
| Enable History Segment Prune<br> | 837 G, \-63% | 1001.25 G, \-60% |

_Originally posted by @0xbundler in https://github.com/bnb-chain/bsc/pull/2017#issuecomment-1894883376_

**Comment by Turtus** [comment]
thanks
