### ISSUE TITLE
#UX История транзакций, отображение даты и сортировка 

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#18]
Очень не хватает продуманного отображения даты и возможно сортировки. Когда в день хотя бы десяток транзакций, найти что-то в текущей реализации истории - ад.
Подсказка: monobank в помощь, чистый UI и продуманный UX.

**Comment by Turtus** [comment]
неактуально - уже поменяли и есть фильтрация

**Comment by Vadymhr** [comment]
сейчас это не конечная реализация будет еще лучше чуть позже
