### ISSUE TITLE
Missing source code for the play store release

### ISSUE THREAD

**Issue by keraliss** [trustee-wallet/trusteeWallet#180]
Hi,

I was attempting to build your wallet and observed that the source code available corresponds to version `v1.51.1`, while the version listed on the Play Store is `1.51.10`.

Could you please provide the source code for the latest version available on the Play Store? This would greatly help us in testing the reproducibility of the wallet.

Thank you!

**Comment by Turtus** [comment]
@rhrusha please update when will be time

**Comment by rhrusha** [comment]
source code updated
