### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by VikMan-Bittrade** [trustee-wallet/trusteeWallet#2]
Добавить новостную ленту в кошелёк , (крипто новости или новости непосредственно самого кошелька/обновления)

**Comment by PC3PR** [comment]
добавьте темную тему

**Comment by rhrusha** [comment]
> 
> 
> добавьте темную тему

темную тему вынес отдельно, так как не связано с запросом новостной ленты.

**Comment by Turtus** [comment]
done!
