### ISSUE TITLE
#UX Идеи: скролинг Истории транзакций и анимация кнопок Отправить/Получить

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#20]
![photo_2020-03-18_22-58-01 (2)](https://user-images.githubusercontent.com/12554812/77009371-76497280-6970-11ea-9641-edb19c183b9d.jpg)
В Issue 19 [https://github.com/trustee-wallet/trusteeWallet/issues/19#issue-584013378](url) описал расположение истории и кнопок и на идее этого UX предлагаю:

- При скролинге истории транзакций "сворачивать" кнопки со смещением  уменьшая их размер (анимация) . 

- Как вариант с полным исчезновением.

- Если бы История транзакций при скроле не скрывала все элементы (баланс, адрес и т.д), а 
"подныривала" под них, то идея с анимацией кнопок кажется хорошей.

Пример gif: 
![animation](https://user-images.githubusercontent.com/12554812/77011486-a561e300-6974-11ea-9001-aedd122a2e54.gif)

**Comment by Turtus** [comment]
done build 828+
