### ISSUE TITLE
Ошибка при запуске приложения на ios

### ISSUE THREAD

**Issue by stribulsergey** [trustee-wallet/trusteeWallet#21]
Вытащил приложение, установил зависимости, автоматом выполнились jetify и nodify, зашел в директорию ios, выполнил pod install. после чего выполнил react-native run-ios и в результате получил билд отвалился с ошибкой 

error: Could not get GOOGLE_APP_ID in Google Services file from build environment

macos: Catalina 10.15.3
node: v10.15.3
npm: 6.4.1

**Comment by Vadymhr** [comment]
@rhrusha Нужна помощь

**Comment by rhrusha** [comment]
спасибо за обращение, смотрим в чем может быть проблема.

**Comment by stribulsergey** [comment]
@rhrusha есть новости? Вы посмотрели?

**Comment by rhrusha** [comment]
В течении нескольких дней опубликем обновление в котором будет решена эта проблема.

**Comment by Turtus** [comment]
@rhrusha можем закрывать же?

**Comment by rhrusha** [comment]
да, закрываю.
