### ISSUE TITLE
#UX Идеи: Dashboard 

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#23]
![photo_2020-03-24_23-02-09](https://user-images.githubusercontent.com/12554812/77478183-3e39a800-6e26-11ea-959b-8b305c5b35c8.jpg)

![photo_2020-03-24_23-02-10](https://user-images.githubusercontent.com/12554812/77479221-0cc1dc00-6e28-11ea-830f-7b7f0c01be0d.jpg)

По-горизонтальному свайпу конкретного актива получать доступ к быстрым функциям. Это исключает необходимость отдельного выбора актива при использовании обмена и покупки/продажи, что ускоряет и упрощает процесс и схоже с уже реализованным быстрым доступом внутри функции "Отправить" конкретного актива. Имхо - более интуитивный UX.

Функции "добавить актив, сканер QR, настройки" и прочие дополнительные опции расположены в контекстном меню вызываемом тапом по иконке в нижней части экрана (описание в issue #22).

**Comment by Vadymhr** [comment]
@Marabun Добрый день! В первую очередь хочу высказать благодарность за интерес к тому, что мы делаем! И отдельно за множество предложений по улучшению! 
Мы обязательно все изучим и вернемся с фидбэком!

**Comment by Turtus** [comment]
долго висит - думаю можно как закрыть тк дизайн уже поменяли вроде с учетом)
