### ISSUE TITLE
Быстрый доступ к выбору кошельков

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#24]
С учетом возможности иметь более одного кошелька имеется потребность быстрого/удобного доступа к выбору кошельков. Сейчас это реализованно через настройки, переход требует выполнения двух шагов, что не очень удобно. 

Предлагаю упростить доступ к выбору кошельков сократив до одного шага. Простое решение: тап по балансу(общий дашборд) текущего кошелька, механика схожа с переходом в актив.

**Comment by PC3PR** [comment]
> С учетом возможности иметь более одного кошелька имеется потребность быстрого/удобного доступа к выбору кошельков. Сейчас это реализованно через настройки, переход требует выполнения двух шагов, что не очень удобно.

неистово плюсую

Но вижу реализацию "свайп влево-вправо" куда удобней

**Comment by Turtus** [comment]
закрою как дубль https://github.com/trustee-wallet/trusteeWallet/issues/78
