### ISSUE TITLE
Как изменить названия созданных кошельков?

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#25]
Создал несколько кошельков которым были присвоены имена по умолчанию: Trustee wallet 1 и Trustee wallet 2. Кроме того, что  при создании не было предложения дать имя, теперь я его не могу изменить. 

После тщательно просмотрев интерфейс обнаружил в левом верхнем углу иконку... Да эта иконка серьезное испытание. Но это не решает проблему уже созданного кошелька.

**Comment by Turtus** [comment]
- изменить имя уже созданного - если зажать название вверху которое на главном экране - появляется окно редактирования, пока так - наверное сделаем еще в настройках кошелька более "стандартный вид" - пока смотрим как идет

- при создании убрали это поле тк 90% новичков спрашивают зачем имя и используют только один кошелек... по иконке - тоже смотрим - пока новичкам проще это точно

**Comment by Marabun** [comment]
На андроид редактирование работает, а вот на iOS, последняя версия с appstore, нет. У Вас работает?

**Comment by Turtus** [comment]
в понедельник-вторник будет релиз на иос последней версии, в андроиде мы чуть вырвались вперед
