### ISSUE TITLE
Интеграция токена GOLD из Erachain + BTC, USD и других

### ISSUE THREAD

**Issue by icreator** [trustee-wallet/trusteeWallet#26]
Здравствуйте

Можно сделать интеграцию в ваш кошелек нашей блокчейн платформы?
Внутри у нас уже есть биржа децентрализованная.

Мы могли бы вас для нашего сообщества так же рекомендовать как сервис ввода вывода в фиат

пример мобилки есть тут https://erachain.org/home-download  
Наша мобилка написана на TS

Есть описание API для создания транзакций на стороне клиента:  
https://app.swaggerhub.com/apis-docs/Erachain/era-api/

## Токенизация всего
Так же после интеграции можно будет любые токены из нашей платформы вставлять в ваш кошелек. Мы планируем запустить токены на разные валюты и нефть.  
Возможно токенизировать вообще что угодно

## Бот трейдер
Так же у нас есть внешний торговый бот, который написан на Java и его можно настравивать на разные схемы работы - https://github.com/erachain/dex-trader. Он работает в связке с локальной блокчейн-нодой.

**Comment by Vadymhr** [comment]
@icreator  Добрый день!

Спасибо за интерес к нашим продуктам и решениям.

К нам регулярно обращаются за поддержкой разных валют и токенов. Извините, в данный исторический момент мы интегрируем самые популярные криптовалюты. Если Вы сами проведете техническую интеграцию мы приймем Ваши изменения в репозиторий.
