### ISSUE TITLE
Can't run your app

### ISSUE THREAD

**Issue by Daveischappelle** [trustee-wallet/trusteeWallet#27]
I tried to build and install your application, but I had next errors: 
1) webview import
![errors](https://user-images.githubusercontent.com/66939862/84630131-2852f500-aef4-11ea-8cd8-a12076aac225.jpg)
but as I could see WebView was import correctly from react-native-webview, I didnt understand what was wrong
2) problem with moduleName "TrusteeWallet"

Could you help me to correct that? Thanks

**Comment by Turtus** [comment]
have you build it following instructions in github readme? the message you get is when _DEV_ mode is on and react native is running as "react-native run-ios" / "react-native run-android"
