### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mrxspice** [trustee-wallet/trusteeWallet#29]
I find it low security for the Backup phrase, it doesn't have a password protection or FP unlock, it's just wide open. Let's say I have an access to the victim's phone who didn't set any PIN or whatever on the phone, many people just hesitate it or if I found out the PIN to Trustee Wallet then I can easily open the wallet and silently copy the Recovery phrase and later use it on my device to get access to the victim's funds.

It may sound a difficult process but not so much, the point of this that Backup phrase after it was extracted has to be protected with a password or FP as a must requirement. Something like this exists in Coinomi wallet for a long time, and if it wasn't important they wouldn't have implemented it at first place.

**Comment by Turtus** [comment]
Passphrase will be added for advanced users as many of them now still think we could recover backup for example or login with email.
Also we suggest to use PIN on trustee (set separatly after backup seed) and keep your phone away from badasses as "bruteforce cryptoanalyze" will work anyway with or without password encryption

**Comment by Vadymhr** [comment]
Hello dear @mrxspice !
Thanks for the interest in our products and solutions!

Turtus completely right regarding passphrase approach and suggestion to use PIN without FP.

@mrxspice just wanted to clarify if we did understand your request correctly. 
Did you mean just a local password that encrypts seed-phase locally but doesn't effect derivation tree or passphrase protection that effect derivation tree?

**Comment by mrxspice** [comment]
> Hello dear @mrxspice !
> Thanks for the interest in our products and solutions!
> 
> Turtus completely right regarding passphrase approach and suggestion to use PIN without FP.
> 
> @mrxspice just wanted to clarify if we did understand your request correctly.
> Did you mean just a local password that encrypts seed-phase locally but doesn't effect derivation tree or passphrase protection that effect derivation tree?

Yes I meant password that protects a seed phrase itself because if you click on backup again it opens without any password or FP request.

**Comment by Vadymhr** [comment]
@mrxspice thanks!
I think it is a good point to protect seed review with pin or FP when it is enabled. In the same way as we do when confirming tx.

@Turtus what do you think?

**Comment by Turtus** [comment]
heh, this one could be improved yep - before more advanced mnemonic+passphrase users modes

**Comment by Vadymhr** [comment]
@mrxspice thanks a lot for your input! we will add your suggestion in nearest release. We are happy to present you with gifts Trustee branded. Please, share with us to where we can ship it to you, contatc@trustee.deals 

@viktor-manin FYI

**Comment by Turtus** [comment]
fixed in new release - please update from google play - we will update github asap
