### ISSUE TITLE
add dark theme

### ISSUE THREAD

**Issue by rhrusha** [trustee-wallet/trusteeWallet#3]
добавьте темную тему

_Originally posted by @PC3PR in https://github.com/trustee-wallet/trusteeWallet/issues/2#issuecomment-576022636_

**Comment by Turtus** [comment]
++1

**Comment by amaday1624** [comment]
#пожелание @cryptoceo давайте сделаем актив(в который раз в месяц все кто в комьюнити будут скидовать кому сколько не жалко монет той или иной крипты, для стимулирования развитие и крипто дискуссии по проекту

**Comment by m-tymchyk** [comment]
Плюсую! Добавте темную тему :)

**Comment by Vadymhr** [comment]
@m-tymchyk ты пользуешься Трасти? Поделись может еще какими рекомендациями

**Comment by m-tymchyk** [comment]
@Vadymhr, ну еще пару рекомендаций и багов найдется :)

- `bug` При включенном Dark Mode на iOS, Status Bar в приложении белый
- `UI` В списке Assets сделайте более мягкую тень
- `UI` На экране **Account {coin}**. Не очевидно что центральная кнопка с логотипом это переход на страницу адресса.
- Добавьте ротацию адресов (хотя это может запутать не знающих пользователей).
- Когда на балансе 0, при нажатии кнопки *Use all funds* экран блюрится и не разблюривается.

Пока хватит :)

**Comment by Turtus** [comment]
done !

**Comment by Turtus** [comment]
ротация адресов есть для биткоина (в настройках включается "хд воллет", и для юсдт можно сменить на любой адрес из биткоиновских... остальное думаем стоит или нет)
