### ISSUE TITLE
Запрос интеграции токена TIKTOK

### ISSUE THREAD

**Issue by thedeex** [trustee-wallet/trusteeWallet#30]
Запрос на интеграцию.

Название монеты: TIKTOK
Количество символов в дробной части: 4
ID монеты: 1.3.129
блокчейн: DEEX

Полные параметры монеты: https://explorer.deex.exchange/#/assets/TIKTOK

API  https://explorer.deex.exchange/api/apidocs/

Explorer: https://explorer.deex.exchange

**Comment by Vadymhr** [comment]
@thedeex Добрый день!

Спасибо за интерес к нашим продуктам и решениям.

К нам регулярно обращаются за поддержкой разных валют и токенов. Извините, в данный исторический момент мы интегрируем самые популярные криптовалюты. Если Вы сами проведете техническую интеграцию мы приймем Ваши изменения в репозиторий.
