### ISSUE TITLE
UI BUG: 683: при переходе с главного экрана на экран аккаунта на несколько мгновений видна полоса слева

### ISSUE THREAD

**Issue by Turtus** [trustee-wallet/trusteeWallet#55]
тестировала на iphone 7

логи с номером заявки (55) сбросила в телеграм @trustee_support_bot

![photo_2020-12-15_15-15-15](https://user-images.githubusercontent.com/17931030/102219601-5c7d9180-3ee8-11eb-99ee-59dc829cb757.jpg)

**Comment by Vadymhr** [comment]
Особенно заметно на страницах с большим количеством транзакций

**Comment by Turtus** [comment]
700+ fixed
