### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by mrxspice** [trustee-wallet/trusteeWallet#6]
Needs some font fixes between languages selection it has upper and lower case letters shown differently and orthography like spaces.

![photo_2020-02-04_17-39-08 (2)](https://user-images.githubusercontent.com/57131531/73760680-5c641f80-4776-11ea-8b1d-1ca69ee69f03.jpg)
![photo_2020-02-04_17-39-08](https://user-images.githubusercontent.com/57131531/73760682-5c641f80-4776-11ea-9332-b3cdcbf850e1.jpg)
![photo_2020-02-04_17-39-35 (2)](https://user-images.githubusercontent.com/57131531/73760719-6b4ad200-4776-11ea-83c2-8c60e00ad38c.jpg)
![photo_2020-02-04_17-39-35](https://user-images.githubusercontent.com/57131531/73760721-6b4ad200-4776-11ea-883f-3ac7daa8fc8d.jpg)

**Comment by rhrusha** [comment]
Issues resolved in recent versions.
