### ISSUE TITLE
Набор активов для разных кошельков

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#66]
При пользовании несколькими кошельками во всех отображается один и тот же набор активов. Причем в разных кошельках разные активы, но отображаются все!, просто отсутствующие с нулевым балансом. 

![1AFE5691-0C3E-4F17-BD15-2123BBBC372E](https://user-images.githubusercontent.com/12554812/102891252-8abe1c80-4466-11eb-9198-95c1baa6bb92.jpeg)

Предлагаю разделять активы, уникальность наборов для каждого кошелька.

**Comment by Turtus** [comment]
comming soon: работаем над индивидуализацией и сортировками на главном

**Comment by Vadymhr** [comment]
@belyokhin это когда перфоманс решим )

**Comment by Turtus** [comment]
пока в бету выпустили с удалением хотябы индивидуальным монеток - т.е. можно лишние с главной убрать - слайд вправо / корзина
