### ISSUE TITLE
Coins, Tokens (ERC-20, TRC-20)

### ISSUE THREAD

**Issue by PC3PR** [trustee-wallet/trusteeWallet#7]
Сейчас все идет одним списком. Разграничьте их по отдельным вкладкам (Coins, ERC-20, TRC-20)
ИМХО: удобнее будет

**Comment by SYARTeam** [comment]
> Сейчас все идет одним списком. Разграничьте их по отдельным вкладкам (Coins, ERC-20, TRC-20)
> ИМХО: удобнее будет

Согласен

**Comment by Turtus** [comment]
done в настройках, на главном пока нет... на главном тоже?
