### ISSUE TITLE
Инфо о всех комиссиях Продажи

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#75]
В деталях продажи отображается информация лишь о комиссии транзакции. Где взять данные о комиссиях сервисов после проведения продажи?
Я знаю, что они есть на стадии формирования продажи. Нужна возможность видеть это в деталях, после продажи. Я правильно понимаю, что эти комиссии вычитается из баланса кошелька и никак не отражаются в цифрах самой транзакции?

**Comment by Vadymhr** [comment]
@Marabun, спасибо за вопрос!
Все комисси которые Трасти может обработать отображены в чеке.
Но бывают нестандартные ситуации. К примеру, когда валюта в которую продают не совпадает с валютой принимающей карты, происходит конвертация на стороне клиентского банка, согласно его условиям.
В Трасти задействованы множество платежных систем. У каждого банка, который обслуживает карту пользователя, разные условия относительно разных систем. Не часто, но бывает, что банк пользователя может снять дополнительную комиссию при зачислении или списании средств.

**Comment by Marabun** [comment]
Я не заметил две точки под нижнем меню, в темной теме серые элементы... Чек - то что надо! По банкам вопросов нет.

**Comment by Turtus** [comment]
закрываю если порешали)
