### ISSUE TITLE
[Minor Bug] Import wallet name 'false' if not added 

### ISSUE THREAD

**Issue by shivchawla** [trustee-wallet/trusteeWallet#79]
As wallet name is optional, I have noticed that wallet name comes to be '**false**' if not added when importing. Thanks!

**Comment by Turtus** [comment]
will check - which version do you tested?

**Comment by shivchawla** [comment]
I made a build from [23476c9](https://github.com/trustee-wallet/trusteeWallet/commit/23476c9394e395511d16f45cad0256590a3a0b43).

**Comment by Turtus** [comment]
couldnt reproduce it - default name is "Trustee Wallet" + number of wallet

![image](https://user-images.githubusercontent.com/17931030/106935790-dd107f80-672c-11eb-8de0-c01e05fb54bb.png)
