### ISSUE TITLE
Добавление монеты Reddcoin

### ISSUE THREAD

**Issue by denisholub89** [trustee-wallet/trusteeWallet#8]
Добрый день, очень понравился ваш кошелёк, очень удобный и простой в использовании. Хочу спросить, не хотели бы вы добавить ещё одну монетку "reddcoin"? На мой взгляд перспективная крипта, торгую ей с 2017 года.
Заранее спасибо 😉

**Comment by Vadymhr** [comment]
Спасибо за Ваш интерес к нашему продукту! 
На данный момент добавление новых монет за морожено.
Обязательно присмотримся к этой монете когда вернемся к этому вопросу

**Comment by denisholub89** [comment]
Спасибо 😉😊
