### ISSUE TITLE
Единицы измерения комиссии Bitcoin

### ISSUE THREAD

**Issue by Marabun** [trustee-wallet/trusteeWallet#87]
Перейдите на измерение комиссии в  sat/vB, или хотябы  в случае использования bc1. Сейчас, если доверится Trustee, платится завышенная комиссия и расхождение около 20% от mempool.space.

**Comment by Turtus** [comment]
нужно да сделать - это связано еще с тем что большинство на легаси адресах - а там это не так существенно, спасибо что подняли тему

**Comment by Turtus** [comment]
fixed https://github.com/trustee-wallet/trusteeWallet/commit/16b931a8b2ef22478cca3dc52b036d8cffd1263c уже в бетке - и скоро в релизе, с билда 820
спасибо еще раз, это мы даже не свою - чужую либку пришлось пофиксить)
