### ISSUE TITLE
Git tag new releases & update master branch

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#92]
The latest tag is "v1.40.639" from "Nov 9, 2020" https://github.com/trustee-wallet/trusteeWallet/releases/tag/v1.40.639
while the latest release on google-play is: 1.40.799 from March 30, 2021 https://play.google.com/store/apps/details?id=com.trusteewallet
Please tag new releases, so each tag will point to the related commit of the release.
This is needed for reproducible-builds, see related issue: #1
also the code in default branch master is old, last updated "Dec 18, 2020" https://github.com/trustee-wallet/trusteeWallet/branches

**Comment by Turtus** [comment]
thanks for issue - actually we are syncing dev branch with development staging - but you are right tags will be useful for users

**Comment by Turtus** [comment]
next release (coming in few days) will be tagged)

**Comment by rhrusha** [comment]
all are done
