### ISSUE TITLE
+ в активы VeChain, Cardano

### ISSUE THREAD

**Issue by Ger-Major** [trustee-wallet/trusteeWallet#95]
Большая просьба добавить в кошелек поддержку активов - VeChain (VET) , Cardano (ADA).

**Comment by Turtus** [comment]
будет

**Comment by Ger-Major** [comment]
> будет

**Comment by Turtus** [comment]
vechain done

**Comment by Ger-Major** [comment]
> 
> 
> vechain done

Fine, thank you!
