### ISSUE TITLE
Move devDependencies that required to compile the app to dependencies

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#96]
rn-nodeify used in build instructions:
https://github.com/trustee-wallet/trusteeWallet#android-build
and in postinstall:
https://github.com/trustee-wallet/trusteeWallet/blob/87a69423484a36e1199030920413154ea3a91453/package.json#L11
is in `devDependencies` instead of `dependencies`:
https://github.com/trustee-wallet/trusteeWallet/blob/87a69423484a36e1199030920413154ea3a91453/package.json#L175
ensure all dependencies used to compile the android & ios version are in dependencies, and compilation work when `NODE_ENV="production"` environment variable is used.

**Comment by Turtus** [comment]
good point - @rhrusha plz check how do we build in prod if its breaking - i could move all from dev - but not sure all other are needed

**Comment by emanuelb** [comment]
Only small subset need to be moved from devDeps to Deps, as I didn't compile the iOS version, don't know about the full list, also after compiling it's worth to compare generated file to APK/IPA build with devDeps installed (with diffoscope tool https://diffoscope.org) as well to ensure it's not affecting the output, less deps installed in release build-process is better which can be achieved by moving only the needed deps for compilation from DevDeps to Deps.

**Comment by Turtus** [comment]
@rhrusha could you update state?

**Comment by Turtus** [comment]
ive done https://github.com/trustee-wallet/trusteeWallet/tree/dev
