### ISSUE TITLE
Missing lockfile package-lock.json or yarn.lock

### ISSUE THREAD

**Issue by emanuelb** [trustee-wallet/trusteeWallet#97]
The repo doesn't contain a lockfile such as `package-lock.json` (when npm used) or `yarn.lock` (when yarn used) files, which enable reproducible-builds as the same versions can be used when rebuilding the app by using `npm ci` command which currently fail with error.

fix: include lockfile in the repo, and ensure app compilation work when `npm ci` or `yarn install --frozen-lockfile` is used to install deps (needed for reproducible deps installation), see related issue #96

**Comment by Turtus** [comment]
@emanuelb actually i did it with purpose to make each build with latest modules - as there are a lot of bugfixes sometime - minus fixed versions - but @rhrusha plz check what about verifiable builds task

**Comment by emanuelb** [comment]
The lockfile is not forcing the usage of same versions, they can be still installed to newer, etc.. but it allows to know what versions are currently used in the commit/tag, and use the exact same versions, thus helping reproducibility, thus it's better to publish the lock file in repo & update it when changed to deps in package.json happen as well.

in case `package-lock.json` will be used (generated by npm) consider using the newer v2 lockfile format which is generated by npm 7 (check that app compilation work when using npm 7, etc...)

https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile
> The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree.

**Comment by Turtus** [comment]
ive done https://github.com/trustee-wallet/trusteeWallet/tree/dev
